@startuml
Modele -> Modele : notifyObservers()
Modele -> VueJeu : update()
VueJeu -> Modele : getTerrain()
VueJeu --> Modele : Terrain t
Modele --> Terrain : getEpoque()
 --> Terrain : getEpoque()


@enduml
